<?php

namespace SD6Production\PopupInfosBundle\Repository;

/**
 * PopupPinnedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PopupPinnedRepository extends \Doctrine\ORM\EntityRepository
{
}
