sd6_production_admin:
    resource: "@SD6ProductionAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

sd6_production_popup_infos:
    resource: "@SD6ProductionPopupInfosBundle/Resources/config/routing.yml"
    prefix:   /

sd6_production_social:
    resource: "@SD6ProductionSocialBundle/Resources/config/routing.yml"
    prefix:   /

sd6_production_contact:
    resource: "@SD6ProductionContactBundle/Resources/config/routing.yml"
    prefix:   /

sd6_production_utilisateur:
    resource: "@SD6ProductionUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

sd6_production_app:
    resource: "@SD6ProductionAppBundle/Resources/config/routing.yml"
    prefix:   /
