sd6_production_social:
    resource: "@SD6ProductionSocialBundle/Resources/config/routing.yml"
    prefix:   /

sd6_production_contact:
    resource: "@SD6ProductionContactBundle/Resources/config/routing.yml"
    prefix:   /

sd6_production_utilisateur:
    resource: "@SD6ProductionUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

sd6_production_app:
    resource: "@SD6ProductionAppBundle/Resources/config/routing.yml"
    prefix:   /
