# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        SD6Production\UtilisateurBundle\Entity\Utilisateur: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main_provider:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main_provider
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /

    access_control:
        #- { path: ^/add, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/logout, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        #- { path: ^/edit, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        #- { path: ^/delete, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/change-password, roles: ROLE_SUPER_ADMIN }
        - { path: ^/register, roles: ROLE_SUPER_ADMIN }
