sd6_production_admin_add:
    path:     /add
    defaults: { _controller: SD6ProductionAdminBundle:Default:add }

sd6_production_admin_edite_advert:
    path:     /annonce/edite/{slugAdvert}
    defaults: { _controller: SD6ProductionAdminBundle:Default:editeAdvert }
    requirements:
        slugAdvert: "[a-zA-Z0-9-]+"

sd6_production_admin_edite_image:
    path:     /image/edite/{idImage}
    defaults: { _controller: SD6ProductionAdminBundle:Default:editeImage }
    requirements:
      idImage: "[0-9-]+"

sd6_production_admin_delete:
  path:     /delete/{typeElement}/{numElement}
  defaults: { _controller: SD6ProductionAdminBundle:Default:delete}
  requirements:
    typeElement: "[a-zA-Z-]+"
    numElement: "[0-9-]+"

sd6_production_admin_member:
    resource: "@SD6ProductionAdminBundle/Resources/config/routing/member.yml"
    prefix:   /membre

sd6_production_admin_category:
    resource: "@SD6ProductionAdminBundle/Resources/config/routing/category.yml"
    prefix:   /categorie

sd6_production_admin_account:
  resource: "@SD6ProductionAdminBundle/Resources/config/routing/account.yml"
  prefix:   /compte
