sd6_production_app_homepage:
    path:     /
    defaults: { _controller: SD6ProductionAppBundle:Default:index }

sd6_production_app_productions:
    path:     /productions
    defaults: { _controller: SD6ProductionAppBundle:Default:productions }

sd6_production_app_prestations:
    path:     /prestations
    defaults: { _controller: SD6ProductionAppBundle:Default:prestations }

sd6_production_app_equipe:
    path:     /equipe
    defaults: { _controller: SD6ProductionAppBundle:Default:equipe }

sd6_production_app_actualites:
    path:     /actualites
    defaults: { _controller: SD6ProductionAppBundle:Default:actualites }

sd6_production_app_photos:
    path:     /galerie-photos
    defaults: { _controller: SD6ProductionAppBundle:Default:photos }

sd6_production_app_casting:
    path:     /casting
    defaults: { _controller: SD6ProductionAppBundle:Default:casting }

sd6_production_app_details_advert:
    path:     /detail/{typeAdvert}/{slugAdvert}
    defaults: { _controller: SD6ProductionAppBundle:Default:detailsAdvert }
    requirements:
        typeAdvert: "[a-zA-Z]+"
        slugAdvert: "[a-zA-Z0-9-]+"
