sd6_production_app_homepage:
    path:     /
    defaults: { _controller: SD6ProductionAppBundle:Default:index }

sd6_production_app_ajout:
    path:     /ajouter
    defaults: { _controller: SD6ProductionAppBundle:Default:ajouter }

sd6_production_app_editionannonce:
    path:     /editer-annonce
    defaults: { _controller: SD6ProductionAppBundle:Default:editerannonce }

sd6_production_app_supprimeannonce:
    path:     /supprimer-annonce
    defaults: { _controller: SD6ProductionAppBundle:Default:supprimerannonce }

sd6_production_app_productions:
    path:     /productions
    defaults: { _controller: SD6ProductionAppBundle:Default:productions }

sd6_production_app_equipe:
    path:     /equipe
    defaults: { _controller: SD6ProductionAppBundle:Default:equipe }

sd6_production_app_actualites:
    path:     /actualites
    defaults: { _controller: SD6ProductionAppBundle:Default:actualites }

sd6_production_app_photos:
    path:     /galerie-photos
    defaults: { _controller: SD6ProductionAppBundle:Default:photos }

sd6_production_app_recrutements:
    path:     /recrutements
    defaults: { _controller: SD6ProductionAppBundle:Default:recrutements }

sd6_production_app_contact:
    path:     /contact
    defaults: { _controller: SD6ProductionAppBundle:Default:contact }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
