sd6_production_app_add:
    path:     /admin/add
    defaults: { _controller: SD6ProductionAppBundle:Action:add }

sd6_production_app_edite_advert:
    path:     /admin/annonce/edite/{slugAdvert}
    defaults: { _controller: SD6ProductionAppBundle:Action:editeAdvert }
    requirements:
        slugAdvert: "[a-zA-Z0-9-]+"

sd6_production_app_edite_image:
    path:     /admin/image/edite/{idImage}
    defaults: { _controller: SD6ProductionAppBundle:Action:editeImage }
    requirements:
      idImage: "[0-9-]+"

sd6_production_app_edite_member:
    path:     /admin/membre/edite/{idMember}
    defaults: { _controller: SD6ProductionAppBundle:Action:editeMember }
    requirements:
      idMember: "[0-9-]+"

sd6_production_app_edite_category:
    path:     /admin/categorie/edite/{idCategory}
    defaults: { _controller: SD6ProductionAppBundle:Action:editeCategory}
    requirements:
      idCategory: "[0-9-]+"

sd6_production_app_delete:
    path:     /admin/delete/{typeElement}/{numElement}
    defaults: { _controller: SD6ProductionAppBundle:Action:delete}
    requirements:
      typeElement: "[a-zA-Z-]+"
      numElement: "[0-9-]+"

sd6_production_app_homepage:
    path:     /
    defaults: { _controller: SD6ProductionAppBundle:Default:index }

sd6_production_app_productions:
    path:     /productions
    defaults: { _controller: SD6ProductionAppBundle:Default:productions }

sd6_production_app_prestations:
    path:     /prestations
    defaults: { _controller: SD6ProductionAppBundle:Default:prestations }

sd6_production_app_equipe:
    path:     /equipe
    defaults: { _controller: SD6ProductionAppBundle:Default:equipe }

sd6_production_app_actualites:
    path:     /actualites
    defaults: { _controller: SD6ProductionAppBundle:Default:actualites }

sd6_production_app_photos:
    path:     /galerie-photos
    defaults: { _controller: SD6ProductionAppBundle:Default:photos }

sd6_production_app_casting:
    path:     /casting
    defaults: { _controller: SD6ProductionAppBundle:Default:casting }

sd6_production_app_details_advert:
    path:     /{typeAdvert}/{slugAdvert}
    defaults: { _controller: SD6ProductionAppBundle:Default:detailsAdvert }
    requirements:
        typeAdvert: "[a-zA-Z]+"
        slugAdvert: "[a-zA-Z0-9-]+"

sd6_production_app_category:
    path:     /categorie
    defaults: { _controller: SD6ProductionAppBundle:Default:category }
