sd6_production_app_homepage:
    path:     /
    defaults: { _controller: SD6ProductionAppBundle:Default:index }

sd6_production_app_productions:
    path:     /productions
    defaults: { _controller: SD6ProductionAppBundle:Default:productions }

sd6_production_app_equipe:
    path:     /equipe
    defaults: { _controller: SD6ProductionAppBundle:Default:equipe }

sd6_production_app_actualites:
    path:     /actualites
    defaults: { _controller: SD6ProductionAppBundle:Default:actualites }

sd6_production_app_photos:
    path:     /galerie-photos
    defaults: { _controller: SD6ProductionAppBundle:Default:photos }

sd6_production_app_recrutements:
    path:     /recrutements
    defaults: { _controller: SD6ProductionAppBundle:Default:recrutements }

sd6_production_app_contact:
    path:     /contact
    defaults: { _controller: SD6ProductionAppBundle:Default:contact }

sd6_production_app_details_annonce:
    path:     /{typeAnnonce}/{slugAnnonce}
    defaults: { _controller: SD6ProductionAppBundle:Default:detailsAnnonce }
    requirements:
        typeAnnonce: "[a-zA-Z]+"
        nomAnnonce: "[a-zA-Z0-9-]+"



sd6_production_app_ajout:
    path:     /ajouter
    defaults: { _controller: SD6ProductionAppBundle:Action:ajouter }

sd6_production_app_edition_annonce:
    path:     annonce/editer/{slugAnnonce}
    defaults: { _controller: SD6ProductionAppBundle:Action:editerAnnonce }
    requirements:
        slugAnnonce: "[a-zA-Z0-9-]+"

sd6_production_app_supprime_annonce:
    path:     /supprimer/{idAnnonce}
    defaults: { _controller: SD6ProductionAppBundle:Action:supprimerAnnonce }
    requirements:
        idAnnonce: "[0-9]+"

sd6_production_app_edition_image:
    path:     image/editer/{idImage}
    defaults: { _controller: SD6ProductionAppBundle:Action:editerImage }
