sd6_production_popup_infos_homepage:
    path:     /
    defaults: { _controller: SD6ProductionAppBundle:Default:index }

sd6_production_popup_infos_create_cookies:
    path:     /create-cookie
    defaults: { _controller: SD6ProductionPopupInfosBundle:Cookies:createCookies }

sd6_production_popup_infos_cgu_cookies:
    path:     /conditions-generales-utilisation
    defaults: { _controller: SD6ProductionPopupInfosBundle:Cookies:cguCookies }

sd6_production_popup_infos_create:
    path:     /admin/popup-pinned/create
    defaults: { _controller: SD6ProductionPopupInfosBundle:Default:create }

sd6_production_popup_infos_edite:
    path:     /admin/popup-pinned/edite/{idPopup}
    defaults: { _controller: SD6ProductionPopupInfosBundle:Default:edite }
    requirements:
      idPopup: "[0-9-]+"

sd6_production_popup_infos_delete:
    path:     /admin/popup-pinned/delete/{idPopup}
    defaults: { _controller: SD6ProductionPopupInfosBundle:Default:delete }
    requirements:
      idPopup: "[0-9-]+"

sd6_production_popup_infos_all:
    path:     /admin/popup-pinned/all
    defaults: { _controller: SD6ProductionPopupInfosBundle:Default:all }
