<?php

namespace SD6Production\AppBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
  public function getAdvertCategories($categoryName){
		$qb = $this->createQueryBuilder('a');

		$qb->join('a.category', 'cat')
		->addSelect('cat');

		$qb->where('cat.name = :catName')
		->setParameter('catName', $categoryName);

		$qb->andWhere('a.published = :published')
		->setParameter('published', true)
		->orderBy('a.date', 'DESC');

		return $qb
		->getQuery()
		->getResult();
	}

	public function getAdvertNb($nbAdvert){
		$qb = $this->createQueryBuilder('a');

		$qb->where('a.published = :published')
		->setParameter('published', true)
		->orderBy('a.date', 'DESC')
		->setMaxResults($nbAdvert);

		return $qb
		->getQuery()
		->getResult();
	}

	public function getAdvertNbWithCategory($nbAdvert, $categoryNom){
		$qb = $this->createQueryBuilder('a');

		$qb->join('a.category', 'cat')
		->addSelect('cat');

		$qb->where('cat.name = :catName')
		->setParameter('catName', $categoryNom);

		$qb->andWhere('a.published = :published')
		->setParameter('published', true)
		->orderBy('a.date', 'DESC')
		->setMaxResults($nbAdvert);

		return $qb
		->getQuery()
		->getResult();
	}
}
