<?php

namespace SD6Production\AppBundle\Repository;

/**
 * AdvertCastingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertCastingRepository extends \Doctrine\ORM\EntityRepository
{
}
