<?php

namespace SD6Production\AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCategory($category){
		$qb = $this->createQueryBuilder('cat');

    $qb->where('cat.name = :catName')
		->setParameter('catName', $category);

		return $qb;
	}

  public function getCategoryWithout($category){
		$qb = $this->createQueryBuilder('cat');

		$qb->where($qb->expr()->notIn('cat.name', ':category'))
    ->setParameter('category', $category);

		$qb->orderBy('cat.name', 'ASC');

		return $qb;
	}
}
