sd6_production_admin_account_index:
  path: /
  defaults: { _controller: SD6ProductionAdminBundle:Account:account }

sd6_production_admin_edite_account:
    path:     /edite/{idAccount}
    defaults: { _controller: SD6ProductionAdminBundle:Account:edite}
    requirements:
      idAccount: "[0-9-]+"

sd6_production_admin_add_account:
    path:     /add/
    defaults: { _controller: SD6ProductionAdminBundle:Account:add}

sd6_production_admin_delete_account:
  path:     /delete/{numAccount}
  defaults: { _controller: SD6ProductionAdminBundle:Account:delete}
  requirements:
    numAccount: "[0-9-]+"
