sd6_production_admin_edite_advert:
    path:     /edite/{idAdvert}
    defaults: { _controller: SD6ProductionAdminBundle:Advert:edite}
    requirements:
      idAdvert: "[0-9-]+"

sd6_production_admin_add_advert:
    path:     /add/
    defaults: { _controller: SD6ProductionAdminBundle:Advert:add}

sd6_production_admin_delete_advert:
  path:     /delete/{idAdvert}
  defaults: { _controller: SD6ProductionAdminBundle:Advert:delete}
  requirements:
    idAdvert: "[0-9-]+"

sd6_production_admin_advert_index:
    path:     /
    defaults: { _controller: SD6ProductionAdminBundle:Advert:advert }
