sd6_production_admin_edite_image:
    path:     /edite/{idImage}
    defaults: { _controller: SD6ProductionAdminBundle:Image:edite}
    requirements:
      idImage: "[0-9-]+"

sd6_production_admin_add_image:
    path:     /add/
    defaults: { _controller: SD6ProductionAdminBundle:Image:add}

sd6_production_admin_delete_image:
  path:     /delete/{numImage}
  defaults: { _controller: SD6ProductionAdminBundle:Image:delete}
  requirements:
    numImage: "[0-9-]+"

sd6_production_admin_image_index:
    path:     /
    defaults: { _controller: SD6ProductionAdminBundle:Image:image }
